POST http://localhost:8000/actuator/busrefresh

###
POST http://localhost:8000/user/login
Content-Type: application/json

{
  "email" : "test2@naver.com"
  , "password" : "test1234"
}

###
POST http://localhost:8000/user/users
Content-Type: application/json

{
  "email" : "test2@naver.com"
  , "pwd" : "test1234"
  , "name" : "테스xx"
}

###

GET http://localhost:8000/user/health_check
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI4OWExM2UyOC05MWZhLTRlYzQtYWM1Ny0wMWExZGZmN2ExM2UiLCJleHAiOjE2NjE4NjYxMjN9.0QFDsXU40Z3zOiRkumwT36LtTmyZYF6j9hoVS5c51vp8tEcoIUxuEDMuhRleeXqKKvAnifTaoxEqhFZunZF74Q

###
GET http://localhost:8000/user/users/10eba8a3-aba2-499a-9bfa-996971ccb8e9
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxYzFkYjFjMS04MTI4LTQ4MTctYjNmZi0wZjU2N2IxZTE1MjYiLCJleHAiOjE2NjE4NjU3MTN9.YGIuscrk_nINkE657Vht7G9xm_hG2QXiPeiEDkl4IUinZDK62_fDc7Jo_tUoXIxlYi-cXroCd-_fBngjgWo0Eg