

###
POST http://localhost:8000/actuator/busrefresh

###
POST http://localhost:8000/user/login
Content-Type: application/json

{
  "email" : "test2@naver.com"
  , "password" : "test1234"
}

###
POST http://localhost:8000/user/users
Content-Type: application/json

{
  "email" : "test2@naver.com"
  , "pwd" : "test1234"
  , "name" : "테스xx"
}

###

GET http://localhost:8000/user/health_check
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1MjlmMmEzNy02ODFjLTQ5YzUtYmEwNS1lMmE4NjU3ZjVhMTgiLCJleHAiOjE2NjI1NTI0MjV9.66_btk9ssTA7UVuKmLuX19HA1oZ4sEsXLHFSZcbZcHdlsmu8HtgP6KDM_nO0RhVKpjJIR6EKqL_BS1BmMCrzmQ

###
GET http://localhost:8000/user/users/529f2a37-681c-49c5-ba05-e2a8657f5a18
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1MjlmMmEzNy02ODFjLTQ5YzUtYmEwNS1lMmE4NjU3ZjVhMTgiLCJleHAiOjE2NjI1NTI0MjV9.66_btk9ssTA7UVuKmLuX19HA1oZ4sEsXLHFSZcbZcHdlsmu8HtgP6KDM_nO0RhVKpjJIR6EKqL_BS1BmMCrzmQ


